#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    error_page 404 /404.html;
    location /404 {
    root /var/www/html;
    internal;
    }
}" > /etc/nginx/sites-enabled/default
sudo service nginx restart
