#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy 
sudo service haproxy start
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo sed -i '/errorfile 504 \/etc\/haproxy\/errors\/504.http/ a \\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back' /etc/haproxy/haproxy.cfg
sudo sed -i '/default_backend http_back/ a \\nbackend http_back\n\tbalance roundrobin\n\tserver 3497-web-01 34.75.84.58:80 check\n\tserver 3497-web-02 54.91.152.39:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
