#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo service haproxy start
sudo chmod 777/etc/haproxy/haproxy.cfg
sudo sed -i '11 i ENABLE=1' /etc/default/haproxy
sudo sed -i '35 a \\nfrontend myfronted\n\tbind *:80\n\tmode http\n\tdefault_backend my_servers' /etc/haproxy/haproxy.cfg
sudo sed -i '39 a \\nbackend my_servers\n\tbalance roundrobin\n\tmode http\n\tserver 3497-web-01 34.75.84.58:80 check\n\tserver 3497-web-02 54.91.152.39 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
