#!/usr/bin/env bash
# This script print ten times'Best School' with hi
x=0
while [ $x -lt 11 ]
do
    if [[ $x -eq 9 ]]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    x=$(( x + 1 ))
done