#!/usr/bin/env bash
# This script print "bad luck from China", "bad luck from China" and "bad luck from Italy"
x=1
while [ $x -le 20 ]
do
    echo "$x"
    case $x in
        4)
        echo "bad luck from China"
        ;;

        9)
        echo "bad luck from China"
        ;;

        17)
        echo "bad luck from Italy"
        ;;
    esac
    x=$(( x+1 ))
done
