#!/usr/bin/env bash
# This script print 12 hours for 59 minutes
H=0 
M=1
while [ $H -le 12 ]
do
    echo "Hour: $H"
    while [ $M -le 59 ]
    do
        echo $M
        M=$(( M+1 ))
    done
    M=1
    H=$(( H+1))
done
