#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.prev
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.prev
sed -i '1i 8.8.8.8    facebook.com' ~/hosts.prev
cp -f ~/hosts.prev /etc/hosts
