#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# Write a Bash script that configures the container to fit the above requirements

pkill -f apache2
apt-get update
sudo apt-get -y upgrade
apt-get install -y nginx
sudo service nginx start
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo - u service nginx restart
